### ISSUE TITLE
Links aren't valid anymore

### ISSUE THREAD

**Issue by jakeisnt** [mrVanDalo/landingpage#3]
The links for most of your projects seem to be no longer functional. You're likely not using the domain `palovandalo.com`, and it looks like all of the links on your personal website (and other projects) point to the domain. Just a heads up if you've forgotten : )

**Comment by mrVanDalo** [comment]
Thanks @jakeisnt for the info. I'll have a look theses days.

**Comment by mrVanDalo** [comment]
https://mrvandalo.github.io/landingpage/ < all links seem to be valid, closing this ticket (after all these years 🥹)
